"""
RMT64 d(1..5) reference values from MTToolBox
calc_equidist (auto-generated by tests/_gen_mttoolbox_reference.py).

Edit docs/library/*_params.yaml and re-run the generator instead
of editing this file directly.
"""

RMT_MTTOOLBOX_D5 = {
    'rmt521': [0, 0, 0, 0, 0],   # mexp=521
    'rmt607': [0, 0, 0, 0, 0],   # mexp=607
    'rmt1279': [0, 0, 0, 0, 0],   # mexp=1279
    'rmt2281': [0, 1, 1, 0, 1],   # mexp=2281
    'rmt4253': [0, 0, 0, 0, 0],   # mexp=4253
}
