"""
dSFMT d(1..5) reference values from MTToolBox
calc_equidist (auto-generated by tests/_gen_mttoolbox_reference.py).

Edit docs/library/*_params.yaml and re-run the generator instead
of editing this file directly.
"""

DSFMT_MTTOOLBOX_D5 = {
    'dsfmt521': [1, 0, 1, 0, 0],   # mexp=521
    'dsfmt1279': [1, 1, 1, 1, 1],   # mexp=1279
    'dsfmt2203': [1, 1, 1, 0, 0],   # mexp=2203
    'dsfmt4253': [1, 0, 1, 1, 0],   # mexp=4253
    'dsfmt11213': [4, 0, 1, 1, 0],   # mexp=11213
    'dsfmt19937': [1, 2, 1, 2, 1],   # mexp=19937
    'dsfmt44497': [1, 1, 0, 0, 1],   # mexp=44497
}
