"""
MersenneTwister d(1..5) reference values from MTToolBox
calc_equidist (auto-generated by tests/_gen_mttoolbox_reference.py).

Edit docs/library/*_params.yaml and re-run the generator instead
of editing this file directly.
"""

MT_MTTOOLBOX_D5 = {
    'mt19937': [0, 0, 405, 0, 249],   # mexp=19937
}
