"""
SFMT d(1..5) reference values from MTToolBox
calc_equidist (auto-generated by tests/_gen_mttoolbox_reference.py).

Edit docs/library/*_params.yaml and re-run the generator instead
of editing this file directly.
"""

SFMT_MTTOOLBOX_D5 = {
    'sfmt607': [3, 3, 2, 3, 1],   # mexp=607
    'sfmt1279': [6, 3, 2, 3, 3],   # mexp=1279
    'sfmt2281': [4, 1, 0, 2, 2],   # mexp=2281
    'sfmt4253': [1, 2, 1, 3, 2],   # mexp=4253
    'sfmt11213': [6, 2, 2, 3, 2],   # mexp=11213
    'sfmt19937': [1, 3, 1, 2, 3],   # mexp=19937
    'sfmt44497': [7, 1, 1, 1, 3],   # mexp=44497
}
