"""
SFMT d(v) reference values from MTToolBox samples/sfmtdc/calc_equidist.

Generated by running calc_equidist -v on each variant's standard parameters
(from sfmt-1.5.1 SFMT-paramsNNN.h, including parity vector). Values are the
32-bit upper-bit equidistribution defect d(v) = N*v - k(v) for v=1..32.

Authoritative reference for tests/test_simd_notprimitive.py.
"""

# (mexp, pos1, sl1, sl2, sr1, sr2, msk[4], parity[4])
SFMT_FULL_PARAMS = {
    607:   (2,   15, 3, 13, 3,
            [0xfdff37ff, 0xef7f3f7d, 0xff777b7d, 0x7ff7fb2f],
            [0x00000001, 0x00000000, 0x00000000, 0x5986f054]),
    1279:  (7,   14, 3,  5, 1,
            [0xf7fefffd, 0x7fefcfff, 0xaff3ef3f, 0xb5ffff7f],
            [0x00000001, 0x00000000, 0x00000000, 0x20000000]),
    2281:  (12,  19, 1,  5, 1,
            [0xbff7ffbf, 0xfdfffffe, 0xf7ffef7f, 0xf2f7cbbf],
            [0x00000001, 0x00000000, 0x00000000, 0x41dfa600]),
    4253:  (17,  20, 1,  7, 1,
            [0x9f7bffff, 0x9fffff5f, 0x3efffffb, 0xfffff7bb],
            [0xa8000001, 0xaf5390a3, 0xb740b3f8, 0x6c11486d]),
    11213: (68,  14, 3,  7, 3,
            [0xeffff7fb, 0xffffffef, 0xdfdfbfff, 0x7fffdbfd],
            [0x00000001, 0x00000000, 0xe8148000, 0xd0c7afa3]),
    19937: (122, 18, 1, 11, 1,
            [0xdfffffef, 0xddfecb7f, 0xbffaffff, 0xbffffff6],
            [0x00000001, 0x00000000, 0x00000000, 0x13c9e684]),
}

# d(1..32) per MTToolBox calc_equidist (32-bit upper-bit accuracy).
SFMT_MTTOOLBOX_D32 = {
    607: [
        3, 3, 2, 3, 1, 1, 2, 3, 5, 0, 3, 6, 5, 3, 0, 1,
        10, 12, 10, 9, 7, 6, 5, 5, 4, 3, 2, 1, 0, 0, 3, 2,
    ],
    1279: [
        6, 3, 2, 3, 3, 1, 2, 3, 2, 3, 2, 4, 10, 11, 9, 3,
        30, 26, 27, 23, 20, 18, 15, 13, 11, 9, 7, 5, 4, 2, 1, 3,
    ],
    2281: [
        4, 1, 0, 2, 2, 2, 1, 1, 1, 3, 3, 6, 8, 22, 12, 2,
        38, 49, 44, 42, 36, 31, 27, 23, 19, 15, 12, 9, 6, 4, 1, 3,
    ],
    4253: [
        1, 2, 1, 3, 2, 0, 3, 3, 32, 17, 14, 2, 59, 35, 15, 1,
        109, 96, 83, 72, 66, 57, 48, 41, 34, 27, 21, 15, 10, 5, 1, 0,
    ],
    11213: [
        6, 2, 2, 3, 2, 0, 1, 1, 187, 63, 3, 2, 79, 86, 46, 0,
        147, 265, 237, 207, 180, 156, 135, 115, 96, 79, 63, 48, 34, 21, 9, 2,
    ],
    19937: [
        1, 3, 1, 2, 3, 2, 1, 2, 3, 1, 0, 117, 285, 176, 85, 2,
        543, 478, 425, 372, 325, 282, 242, 206, 173, 142, 114, 88, 63, 40, 19, 3,
    ],
}

assert all(len(v) == 32 for v in SFMT_MTTOOLBOX_D32.values())
assert sum(SFMT_MTTOOLBOX_D32[19937]) == 4199
