"""
TinyMT32 d(1..5) reference values from MTToolBox
calc_equidist (auto-generated by tests/_gen_mttoolbox_reference.py).

Edit docs/library/*_params.yaml and re-run the generator instead
of editing this file directly.
"""

TINYMT_MTTOOLBOX_D5 = {
    'tinymt32_default': [0, 0, 0, 0, 0],   # mexp=127
}
