"""
XORSHIFT128 d(1..5) reference values from MTToolBox
calc_equidist (auto-generated by tests/_gen_mttoolbox_reference.py).

Edit docs/library/*_params.yaml and re-run the generator instead
of editing this file directly.
"""

XORSHIFT_MTTOOLBOX_D5 = {
    'marsaglia_20_11_7': [0, 1, 0, 1, 0],   # mexp=128
    'marsaglia_5_14_1': [0, 0, 0, 8, 1],   # mexp=128
}
